<?php
// generated by the algorithm

include "mysql.php";
include "verbose.php";

$factor_class  = 'Observations';

$rel_role = 'diagnose';


if (strcmp($fac_or_rel, "factors") == 0) {
	include "get_data_factor.php";
}
else {
	include "get_data_relation.php";
}


?>
