<?php
// generated by the algorithm

include "mysql.php";
include "verbose.php";
include "game_flow.php";
include 'Text-Statistics/TextStatistics.php';

//echo $_COOKIE["Username"];

if (isset($_COOKIE["Username"])) {
	$wid = $_COOKIE["Username"];
} else {
	mysqli_close($con);
	header('Location: login.php') ;
	exit();
}


function get_par_from_order($doc_id, $doc_order, $con) {
	$query = "SELECT Path FROM game_doc WHERE
	ID = $doc_id";
	$res = mysqli_query($con, $query);
	$statistics = new TextStatistics;
	
	if ($row = mysqli_fetch_array($res)) {
		$file_handle = fopen($row['Path'], "r");
    $text = "";
		while (!feof($file_handle)) {
		 $line = fgets($file_handle);
			 //echo $line;	
			 $text = $text.$line;
		}
		fclose($file_handle);
		
		$xml = simplexml_load_string($text);
		$par_no = 0;
		$par_text = "";
		$result = $xml->xpath("//p");
		//print_r($result);
		while(list( , $node) = each($result)) {
			if ($statistics->word_count($node)) {
				if ($par_no == $doc_order) {
					$par_text = $node;
				}
				$par_no++;
			}
		}
	}
	return $par_text;
}


//$factor_class  = 'Observations';
$rel_role = 'diagnose';

$pid = -1;

$current_score = 0;
$points_gained = 0;
$points_lost = 0;

$query = "SELECT * FROM game_user WHERE
	Name = '$wid' AND
	Worker_role = 'annotate' AND
	Task = 'factors'";
$res = mysqli_query($con, $query);

$exp_group = -1;
if ($row = mysqli_fetch_array($res)) {
	$current_score = $row["Score"];
	$points_gained = round($row["Points_gained"],1);
	$points_lost = round($row["Points_lost"],1);
	//echo $row["Points_gained"]."\n".$row["Points_lost"]."\n\n\n";
	$exp_group = $row["Exp_group"];
}

$pop_text = "";
if ($points_gained == 0) {
	if ($points_lost == 0) {
		$pop_text = "nothing yet";
	}
	else {
		$pop_text = "<span class='trmin'>-$points_lost</span> points deducted by other users disagreeing with your answers";
	}
}
else {
	if ($points_lost == 0) {
		$pop_text = "<span class='trme'>+$points_gained</span> points gained from other users agreeing with your answers";
	}
	else {
		$pop_text = "<p><span class='trme'>+$points_gained</span> points gained from other users agreeing with your answers</p><p><span class='trmin'>-$points_lost</span> points deducted by other users disagreeing with your answers</p>";
	}
}



if (strcmp($fac_or_rel, "factors") == 0) {
	include "get_data_factor.php";
}
else {
	include "get_data_relation.php";
}

$doc_score = par_diff_score($pid, $wid, $con) + 1;

mysqli_close($con);

?>
